### ISSUE TITLE
[VL]Empty map validation failed for Velox

### ISSUE THREAD

**Issue by zhli1142015** [apache/incubator-gluten#3815]
### Backend

VL (Velox)

### Bug description

I think we should allow empty map in substrait validation: https://github.com/oap-project/gluten/blob/c7bce952900a60959c633007b06e55344ac22824/cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc#L271

```
spark.sql("""select map(array(1, i_manufact_id), map()) from item where isnull(i_manufact_id) limit 10""").
show(false)
```
```
23/11/22 16:36:48 WARN GlutenFallbackReporter: Validation failed for plan: Exchange, due to: Found schema check failure in shuffle exchange..
23/11/22 16:36:48 WARN GlutenFallbackReporter: Validation failed for plan: Project, due to: native check failure:native validation failed due to: literal is a map but has no value..
java.lang.UnsupportedOperationException: Input schema contains unsupported type when convert row to columnar, StructType(StructField(map(array(1, i_manufact_id), map()),MapType(ArrayType(IntegerType,true),MapType(NullType,NullType,false),false),false))
  at io.glutenproject.execution.RowToVeloxColumnarExec.doExecuteColumnarInternal(RowToVeloxColumnarExec.scala:50)
  at io.glutenproject.execution.RowToColumnarExecBase.doExecuteColumnar(RowToColumnarExecBase.scala:61)
  at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:221)
  at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229)
  at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:217)
  at org.apache.spark.sql.execution.InputAdapter.doExecuteColumnar(WholeStageCodegenExec.scala:521)
  at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:221)
  at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229)
  at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:217)
  at io.glutenproject.execution.TransformSupport.getColumnarInputRDDs(WholeStageTransformer.scala:81)
  at io.glutenproject.execution.TransformSupport.getColumnarInputRDDs$(WholeStageTransformer.scala:76)
  at io.glutenproject.execution.LimitTransformer.getColumnarInputRDDs(LimitTransformer.scala:37)
  at io.glutenproject.execution.UnaryTransformSupport.columnarInputRDDs(WholeStageTransformer.scala:92)
  at io.glutenproject.execution.UnaryTransformSupport.columnarInputRDDs$(WholeStageTransformer.scala:91)
  at io.glutenproject.execution.LimitTransformer.columnarInputRDDs(LimitTransformer.scala:37)
  at io.glutenproject.execution.TransformSupport.getColumnarInputRDDs(WholeStageTransformer.scala:79)
  at io.glutenproject.execution.TransformSupport.getColumnarInputRDDs$(WholeStageTransformer.scala:76)
  at io.glutenproject.execution.WholeStageTransformer.getColumnarInputRDDs(WholeStageTransformer.scala:96)
  at io.glutenproject.execution.UnaryTransformSupport.columnarInputRDDs(WholeStageTransformer.scala:92)
  at io.glutenproject.execution.UnaryTransformSupport.columnarInputRDDs$(WholeStageTransformer.scala:91)
  at io.glutenproject.execution.WholeStageTransformer.columnarInputRDDs(WholeStageTransformer.scala:96)
  at io.glutenproject.execution.WholeStageTransformer.doExecuteColumnar(WholeStageTransformer.scala:261)
  at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:221)
  at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229)
  at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:217)
  at io.glutenproject.execution.VeloxColumnarToRowExec.doExecuteInternal(VeloxColumnarToRowExec.scala:72)
  at io.glutenproject.execution.ColumnarToRowExecBase.doExecute(ColumnarToRowExecBase.scala:50)
  at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:194)
  at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:190)
  at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.inputRDD$lzycompute(ShuffleExchangeExec.scala:135)
  at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.inputRDD(ShuffleExchangeExec.scala:135)
  at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.mapOutputStatisticsFuture$lzycompute(ShuffleExchangeExec.scala:140)
  at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.mapOutputStatisticsFuture(ShuffleExchangeExec.scala:139)
  at org.apache.spark.sql.execution.exchange.ShuffleExchangeLike.$anonfun$submitShuffleJob$1(ShuffleExchangeExec.scala:68)
  at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229)
  at org.apache.spark.sql.execution.exchange.ShuffleExchangeLike.submitShuffleJob(ShuffleExchangeExec.scala:68)
  at org.apache.spark.sql.execution.exchange.ShuffleExchangeLike.submitShuffleJob$(ShuffleExchangeExec.scala:67)
  at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.submitShuffleJob(ShuffleExchangeExec.scala:115)
  at org.apache.spark.sql.execution.adaptive.ShuffleQueryStageExec.shuffleFuture$lzycompute(QueryStageExec.scala:174)
  at org.apache.spark.sql.execution.adaptive.ShuffleQueryStageExec.shuffleFuture(QueryStageExec.scala:174)
  at org.apache.spark.sql.execution.adaptive.ShuffleQueryStageExec.doMaterialize(QueryStageExec.scala:176)
  at org.apache.spark.sql.execution.adaptive.QueryStageExec.materialize(QueryStageExec.scala:82)
  at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$getFinalPhysicalPlan$5(AdaptiveSparkPlanExec.scala:260)
  at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$getFinalPhysicalPlan$5$adapted(AdaptiveSparkPlanExec.scala:258)
  at scala.collection.Iterator.foreach(Iterator.scala:943)
  at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
  at scala.collection.IterableLike.foreach(IterableLike.scala:74)
  at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
  at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$getFinalPhysicalPlan$1(AdaptiveSparkPlanExec.scala:258)
  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
  at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.getFinalPhysicalPlan(AdaptiveSparkPlanExec.scala:230)
  at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.withFinalPlanUpdate(AdaptiveSparkPlanExec.scala:372)
  at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.executeCollect(AdaptiveSparkPlanExec.scala:345)
  at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:3868)
  at org.apache.spark.sql.Dataset.$anonfun$head$1(Dataset.scala:2863)
  at org.apache.spark.sql.Dataset.$anonfun$withAction$2(Dataset.scala:3858)
  at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:510)
  at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3856)
  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:109)
  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:169)
  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:95)
  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
  at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3856)
  at org.apache.spark.sql.Dataset.head(Dataset.scala:2863)
  at org.apache.spark.sql.Dataset.take(Dataset.scala:3084)
  at org.apache.spark.sql.Dataset.getRows(Dataset.scala:288)
  at org.apache.spark.sql.Dataset.showString(Dataset.scala:327)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:810)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:787)
  ... 47 elided
```

### Spark version

None

**Comment by gaoyangxiaozhu** [comment]
I think this issue can be closed as it already been fxied @rui-mo

**Comment by rui-mo** [comment]
Fixed by https://github.com/apache/incubator-gluten/commit/c2b08058a4e002ebc3ec2138c899e84353d15fc9.
