### ISSUE TITLE
[VL] Add orc char type validation

### ISSUE THREAD

**Issue by kerwin-zk** [apache/incubator-gluten#4796]
### Backend

VL (Velox)

### Bug description

When selecting from a Hive ORC table without including the char column, having a char column in the table can cause exception in Velox's parsing of the file metadata. For instance, if Hive ORC table A has two columns,``` a int``` and ``` b char```, selecting only the integer column with ```select a from A``` will result in the following exception.

```
Error Source: RUNTIME
Error Code: UNKNOWN
Reason: {} not supported yet.CHAR
Retriable: False
Context: Split [Hive: oss:///user/hive/warehouse/tpcds_1000.db/customer/000003_0 64101152 - 7199294] Task Gluten stage-3 task-2073
Top-Level Context: Same as context.
Function: kind
File: ../../velox/dwio/dwrf/common/FileMetadata.cpp
Line: 100
```

### Spark version

Spark-3.2.x

**Comment by kevinwilfong** [comment]
Hi @kerwin-zk I was wondering if you had a repro or a stack trace for this exception.

I suspect it may have been fixed on the Velox side by https://github.com/facebookincubator/velox/pull/10145 and I'm wondering if we can remove this check.

**Comment by kerwin-zk** [comment]
> Hi [@kerwin-zk](https://github.com/kerwin-zk) I was wondering if you had a repro or a stack trace for this exception.
> 
> I suspect it may have been fixed on the Velox side by [facebookincubator/velox#10145](https://github.com/facebookincubator/velox/pull/10145) and I'm wondering if we can remove this check.

@kevinwilfong 
```
Caused by: org.apache.gluten.exception.GlutenException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: CHAR not supported yet.
Retriable: False
Context: Split [Hive: oss:///user/hive/warehouse/user_info_orc/000000_0 0 - 482] Task Gluten_Stage_2_TID_5_VTID_0
Additional Context: Operator: TableScan[0] 0
Function: kind
File: /mnt/disk2/serverless-spark-jenkins/workspace/EMR-Spark-Fusion-Velox/velox/velox/dwio/dwrf/common/FileMetadata.cpp
Line: 105
Stack trace:
# 0  facebook::velox::VeloxException::VeloxException(char const*, unsigned long, char const*, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, bool, facebook::velox::VeloxException::Type, std::basic_string_view<char, std::char_traits<char> >)
# 1  void facebook::velox::detail::veloxCheckFail<facebook::velox::VeloxRuntimeError, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(facebook::velox::detail::VeloxCheckFailArgs const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
# 2  facebook::velox::dwrf::TypeWrapper::kind() const
# 3  facebook::velox::dwrf::ReaderBase::convertType(facebook::velox::dwrf::FooterWrapper const&, unsigned int, bool)
# 4  facebook::velox::dwrf::ReaderBase::convertType(facebook::velox::dwrf::FooterWrapper const&, unsigned int, bool)
# 5  facebook::velox::dwrf::ReaderBase::ReaderBase(facebook::velox::dwio::common::ReaderOptions const&, std::unique_ptr<facebook::velox::dwio::common::BufferedInput, std::default_delete<facebook::velox::dwio::common::BufferedInput> >)
# 6  facebook::velox::dwrf::DwrfReader::DwrfReader(facebook::velox::dwio::common::ReaderOptions const&, std::unique_ptr<facebook::velox::dwio::common::BufferedInput, std::default_delete<facebook::velox::dwio::common::BufferedInput> >)
# 7  facebook::velox::dwrf::DwrfReader::create(std::unique_ptr<facebook::velox::dwio::common::BufferedInput, std::default_delete<facebook::velox::dwio::common::BufferedInput> >, facebook::velox::dwio::common::ReaderOptions const&)
# 8  facebook::velox::orc::OrcReaderFactory::createReader(std::unique_ptr<facebook::velox::dwio::common::BufferedInput, std::default_delete<facebook::velox::dwio::common::BufferedInput> >, facebook::velox::dwio::common::ReaderOptions const&)
# 9  facebook::velox::connector::hive::SplitReader::createReader()
# 10 facebook::velox::connector::hive::SplitReader::prepareSplit(std::shared_ptr<facebook::velox::common::MetadataFilter>, facebook::velox::dwio::common::RuntimeStatistics&)
# 11 facebook::velox::connector::hive::HiveDataSource::addSplit(std::shared_ptr<facebook::velox::connector::ConnectorSplit>)
# 12 facebook::velox::exec::TableScan::getOutput()
# 13 facebook::velox::exec::Driver::runInternal(std::shared_ptr<facebook::velox::exec::Driver>&, std::shared_ptr<facebook::velox::exec::BlockingState>&, std::shared_ptr<facebook::velox::RowVector>&)::{lambda()#10}::operator()() const
# 14 facebook::velox::exec::Driver::runInternal(std::shared_ptr<facebook::velox::exec::Driver>&, std::shared_ptr<facebook::velox::exec::BlockingState>&, std::shared_ptr<facebook::velox::RowVector>&)
# 15 facebook::velox::exec::Driver::next(folly::SemiFuture<folly::Unit>*)
# 16 facebook::velox::exec::Task::next(folly::SemiFuture<folly::Unit>*)
# 17 gluten::WholeStageResultIterator::next()
# 18 Java_org_apache_gluten_vectorized_ColumnarBatchOutIterator_nativeHasNext
# 19 0x00007fd61fae8427

	at org.apache.gluten.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
	at org.apache.gluten.vectorized.ColumnarBatchOutIterator.hasNext0(ColumnarBatchOutIterator.java:57)
	at org.apache.gluten.iterator.ClosableIterator.hasNext(ClosableIterator.java:39)
	... 33 more
```

**Comment by kevinwilfong** [comment]
@kerwin-zk Thanks for providing the stack! It is indeed still an issue
