### ISSUE TITLE
[CH][CI] StackOverflowError at java.base/java.security.AccessController.doPrivileged

### ISSUE THREAD

**Issue by PHILO-HE** [apache/incubator-gluten#5274]
### Backend

CH (ClickHouse)

### Bug description

[Expected behavior] and [actual behavior].

### Spark version

None

### Relevant logs

```bash
java.lang.StackOverflowError
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/jdk.internal.reflect.ClassDefiner.defineClass(ClassDefiner.java:57)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:400)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generateSerializationConstructor(MethodAccessorGenerator.java:112)
	at java.base/jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:514)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:506)
	at java.base/java.io.ObjectStreamClass.getSerializableConstructor(ObjectStreamClass.java:1531)
	at java.base/java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:509)
	at java.base/java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:484)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:484)
	at java.base/java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:381)
	at java.base/java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:225)
	at org.jboss.marshalling.reflect.SerializableClass.<init>(SerializableClass.java:85)
	at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:62)
	at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:59)
	at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
	at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
	at java.base/java.lang.ClassValue.get(ClassValue.java:116)
```

**Comment by PHILO-HE** [comment]
See https://github.com/apache/incubator-gluten/pull/5268

**Comment by PHILO-HE** [comment]
@zzcclp, CH CI fails for new PRs. Could you help check it? Many thanks!

**Comment by PHILO-HE** [comment]
This issue disappears now. Closing it. Thanks!
