### ISSUE TITLE
spillRun.rows.empty() Error

### ISSUE THREAD

**Issue by weiting-chen** [apache/incubator-gluten#5348]
### Backend

VL (Velox)

### Bug description

Reproduce Steps:
Step 1. Generate data.txt via below python script
`To generate file：gen_spill_data.py`

```python
# -*- coding: utf-8 -*-

import random

# define a function to generate a random number from digital length 0 to 20
def random_number_string(length=20):
    range_start = 10**(length-1)
    range_end = (10**length) - 1
    return str(random.randint(range_start, range_end))

# create a writable file if the file does not exist
with open('data.txt', 'w') as file:
    # loop 10000 times
    for _ in range(10000000):
        # generate four random number with the length 0 to 20
        f1 = random_number_string()
        f2 = random_number_string()
        f3 = random_number_string()
        f4 = random_number_string()
        # Write those four number into the file with comma as delimitation
        file.write("{}\t{}\t{}\t{}\n".format(f1, f2, f3, f4))
```

`Use gen_spill_data.py to generate data.txt`
 python gen_spill_data.py
 

Step 2. Create table and import the data
create table unisql.test_spill_02 (f1 string, f2 string, f3 string, f4 string) stored as textfile OPTIONS ('field.delim' = '\t');
hdfs dfs -put -f data.txt hdfs://xxx/user/hive/warehouse/unisql.db/test_spill_02/
create table unisql.test_spill_03 stored as parquet as select * from unisql.test_spill_02 distribute by f1;

Step 3. Launch Gluten and use below parameters to set up the environment：
--executor-memory 1024m
--conf "spark.memory.offHeap.size"="1024m" 
--conf "spark.memory.offHeap.enabled"="true" 

Step 4. Run SQL and check the log
create table unisql.test_spill_bad stored as parquet as
select f1, f2, f3, f4
   ,lag(f2) over(partition by f1 order by cast(f4 as bigint) asc) f5
from unisql.test_spill_03;

### Spark version

Spark-3.2.x

### Spark configurations

--executor-memory 1024m
--conf "spark.memory.offHeap.size"="1024m" 
--conf "spark.memory.offHeap.enabled"="true" 

### Relevant logs

```bash
Caused by: java.lang.RuntimeException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Retriable: False
Expression: spillRun.rows.empty()
Function: checkEmptySpillRuns
File: /app/dps-ssc-core-gluten/ep/build-velox/build/velox_ep/velox/exec/Spiller.cpp
Line: 494
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorENS1_22CompileTimeEmptyStringEEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  _ZNK8facebook5velox4exec7Spiller19checkEmptySpillRunsEv
# 4  _ZN8facebook5velox4exec7Spiller13fillSpillRunsEPKNS1_20RowContainerIteratorE
# 5  _ZN8facebook5velox4exec7Spiller5spillEPKNS1_20RowContainerIteratorE
# 6  _ZN8facebook5velox4exec10SortBuffer5spillEv
# 7  _ZN8facebook5velox4exec10SortBuffer15ensureInputFitsERKSt10shared_ptrINS0_10BaseVectorEE
# 8  _ZN8facebook5velox4exec10SortBuffer8addInputERKSt10shared_ptrINS0_10BaseVectorEE
# 9  _ZN8facebook5velox4exec7OrderBy8addInputESt10shared_ptrINS0_9RowVectorEE
# 10 _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE
# 11 _ZN8facebook5velox4exec6Driver4nextERSt10shared_ptrINS1_13BlockingStateEE
# 12 _ZN8facebook5velox4exec4Task4nextEPN5folly10SemiFutureINS3_4UnitEEE
# 13 _ZN6gluten24WholeStageResultIterator4nextEv
# 14 Java_io_glutenproject_vectorized_ColumnarBatchOutIterator_nativeHasNext
# 15 0x00007f097d017a14
    at io.glutenproject.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method) ~[gluten-velox-bundle-spark3.2_2.12-centos_7-1.1.0.jar:?]
    at io.glutenproject.vectorized.ColumnarBatchOutIterator.hasNextInternal(ColumnarBatchOutIterator.java:65) ~[gluten-velox-bundle-spark3.2_2.12-centos_7-1.1.0.jar:?]
    at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:37) ~[gluten-velox-bundle-spark3.2_2.12-centos_7-1.1.0.jar:?]
    at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:45) ~[scala-library-2.12.15.jar:?]
    at io.glutenproject.utils.IteratorCompleter.hasNext(Iterators.scala:69) ~[gluten-velox-bundle-spark3.2_2.12-centos_7-1.1.0.jar:?]
    at io.glutenproject.utils.PayloadCloser.hasNext(Iterators.scala:35) ~[gluten-velox-bundle-spark3.2_2.12-centos_7-1.1.0.jar:?]
    at io.glutenproject.utils.PipelineTimeAccumulator.hasNext(Iterators.scala:98) ~[gluten-velox-bundle-spark3.2_2.12-centos_7-1.1.0.jar:?]
    at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460) ~[scala-library-2.12.15.jar:?]
    at org.apache.spark.writer.gluten.uniffle.writer.NativeShuffleWriter.writeImpl(NativeShuffleWriter.scala:91) ~[gluten-uniffle-1.0-SNAPSHOT.jar:?]
    at org.apache.spark.writer.gluten.uniffle.writer.NativeShuffleWriter.write(NativeShuffleWriter.scala:73) ~[gluten-uniffle-1.0-SNAPSHOT.jar:?]
    at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59) ~[spark-core_2.12-3.2.1_20230222.jar:3.2.1]
    at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99) ~[spark-core_2.12-3.2.1_20230222.jar:3.2.1]
    at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52) ~[spark-core_2.12-3.2.1_20230222.jar:3.2.1]
    at org.apache.spark.scheduler.Task.run(Task.scala:131) ~[spark-core_2.12-3.2.1_20230222.jar:3.2.1]
    at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506) ~[spark-core_2.12-3.2.1_20230222.jar:3.2.1]
    at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462) ~[spark-core_2.12-3.2.1_20230222.jar:3.2.1]
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509) ~[spark-core_2.12-3.2.1_20230222.jar:3.2.1]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_275]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_275]
    at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_275]
```

**Comment by zhztheplayer** [comment]
I have mirrored the test into Scala and could not reproduce this issue in newest Gluten code.

```scala
// with setting spark.memory.offHeap.size=1g
test("data gen") {
  val df1 = spark.sql(
    "CREATE TABLE test_spill_02(f1 string, f2 string, f3 string, f4 string) USING csv " +
      "OPTIONS (path '/root/Workloads/SF/bug1/data.txt', delimiter '\t')")

  df1.collect()

  val df2 = spark.sql("select * from test_spill_02 distribute by f1")
  df2.write.parquet("/root/Workloads/SF/bug1/parquet")
}

test("simple_select") {
  val df1 = spark.sql(
    "CREATE TABLE test_spill_03(f1 string, f2 string, f3 string, f4 string) USING parquet " +
      "OPTIONS (path '/root/Workloads/SF/bug1/parquet')")

  df1.collect()

  val df2 = spark.sql("select f1, f2, f3, f4\n," +
    "lag(f2) over(partition by f1 order by cast(f4 as bigint) asc) f5\n" +
    "from test_spill_03")

  df2.write.mode(SaveMode.Overwrite).parquet("/root/Workloads/SF/bug1/parquet2")
}
```

So the issue might be already solved if using newest Gluten main code, since Velox's spill code has changed a lot after Gluten 1.1 release @weiting-chen 

Also I'll try obtain a 1.1 binary then test with the case again.

**Comment by zhztheplayer** [comment]
@weiting-chen Do we have chance to get a full spark conf list? I still didn't repeat the issue using 1.1.1 release. Probably related to Spark shuffle settings and I am not sure.

My Spark config list

```
spark.executor.id	driver
spark.gluten.memory.conservative.task.offHeap.size.in.bytes	268435456
spark.gluten.memory.offHeap.size.in.bytes	1073741824
spark.gluten.memory.task.offHeap.size.in.bytes	536870912
spark.gluten.sql.session.timeZone.default	America/Los_Angeles
spark.gluten.ui.enabled	true
spark.hadoop.fs.file.impl	org.apache.spark.DebugFilesystem
spark.master	local[2]
spark.memory.offHeap.enabled	true
spark.memory.offHeap.size	1g
spark.plugins	io.glutenproject.GlutenPlugin
spark.scheduler.mode	FIFO
spark.shuffle.manager	org.apache.spark.shuffle.sort.ColumnarShuffleManager
spark.sql.codegen.factoryMode	CODEGEN_ONLY
spark.sql.codegen.fallback	false
spark.sql.extensions	io.glutenproject.GlutenSessionExtensions
spark.sql.optimizer.excludedRules	org.apache.spark.sql.catalyst.optimizer.ConvertToLocalRelation
spark.sql.testkey	true
spark.sql.warehouse.dir	file:/opt/gluten/spark-warehouse//io.glutenproject.execution.TestOperator
spark.ui.enabled	true
spark.unsafe.exceptionOnMemoryLeak	true
```

The `xxx` dir after all scripts were finished execution:

```
root@55f8ad28c275:~/Workloads/xxx/bug1# tree ./
./
|-- data.txt
|-- gen_spill_data.py
|-- parquet
|   |-- _SUCCESS
|   |-- part-00000-eb408a87-db1b-43ba-8f8e-ad0ff0665529-c000.snappy.parquet
|   |-- part-00001-eb408a87-db1b-43ba-8f8e-ad0ff0665529-c000.snappy.parquet
|   |-- part-00002-eb408a87-db1b-43ba-8f8e-ad0ff0665529-c000.snappy.parquet
|   |-- part-00003-eb408a87-db1b-43ba-8f8e-ad0ff0665529-c000.snappy.parquet
|   `-- part-00004-eb408a87-db1b-43ba-8f8e-ad0ff0665529-c000.snappy.parquet
`-- parquet2
    |-- _SUCCESS
    |-- part-00000-9a38a46e-0e36-40f2-aa9f-385e9855191b-c000.snappy.parquet
    |-- part-00001-9a38a46e-0e36-40f2-aa9f-385e9855191b-c000.snappy.parquet
    |-- part-00002-9a38a46e-0e36-40f2-aa9f-385e9855191b-c000.snappy.parquet
    |-- part-00003-9a38a46e-0e36-40f2-aa9f-385e9855191b-c000.snappy.parquet
    `-- part-00004-9a38a46e-0e36-40f2-aa9f-385e9855191b-c000.snappy.parquet

2 directories, 14 files
```

**Comment by zhztheplayer** [comment]
I used Gluten+Uniffle bundle from newest main code to run the test but still didn't repeat the error.

Spark config (3.2.2):

```
spark.app.id	local-1713511964160
spark.app.name	test-sql-context
spark.app.startTime	1713511959220
spark.driver.host	55f8ad28c275
spark.driver.port	46003
spark.executor.id	driver
spark.gluten.memory.conservative.task.offHeap.size.in.bytes	268435456
spark.gluten.memory.offHeap.size.in.bytes	1073741824
spark.gluten.memory.task.offHeap.size.in.bytes	536870912
spark.gluten.sql.session.timeZone.default	America/Los_Angeles
spark.gluten.ui.enabled	true
spark.hadoop.fs.file.impl	org.apache.spark.DebugFilesystem
spark.master	local[2]
spark.memory.offHeap.enabled	true
spark.memory.offHeap.size	1g
spark.plugins	org.apache.gluten.GlutenPlugin
spark.rss.client.type	GRPC_NETTY
spark.rss.coordinator.quorum	localhost:19999
spark.rss.row.based	false
spark.rss.storage.type	MEMORY_LOCALFILE
spark.scheduler.mode	FIFO
spark.serializer	org.apache.spark.serializer.KryoSerializer
spark.shuffle.manager	org.apache.spark.shuffle.gluten.uniffle.UniffleShuffleManager
spark.shuffle.reduceLocality.enabled	false
spark.shuffle.service.enabled	false
spark.sql.adaptive.localShuffleReader.enabled	false
spark.sql.codegen.factoryMode	CODEGEN_ONLY
spark.sql.codegen.fallback	false
spark.sql.extensions	org.apache.gluten.GlutenSessionExtensions
spark.sql.optimizer.excludedRules	org.apache.spark.sql.catalyst.optimizer.ConvertToLocalRelation
spark.sql.testkey	true
spark.sql.warehouse.dir	file:/opt/gluten/spark-warehouse//org.apache.gluten.execution.TestOperator
spark.ui.enabled	true
spark.unsafe.exceptionOnMemoryLeak	true
```

The xxx dir after all scripts were finished execution:

```
root@55f8ad28c275:~/Workloads/xxx/bug1# tree --du -h ./
./
|-- [801M]  data.txt
|-- [ 760]  gen_spill_data.py
|-- [704M]  parquet
|   |-- [   0]  _SUCCESS
|   |-- [141M]  part-00000-70f39175-7da9-41db-9f80-08e6870be919-c000.snappy.parquet
|   |-- [141M]  part-00001-70f39175-7da9-41db-9f80-08e6870be919-c000.snappy.parquet
|   |-- [141M]  part-00002-70f39175-7da9-41db-9f80-08e6870be919-c000.snappy.parquet
|   |-- [141M]  part-00003-70f39175-7da9-41db-9f80-08e6870be919-c000.snappy.parquet
|   `-- [141M]  part-00004-70f39175-7da9-41db-9f80-08e6870be919-c000.snappy.parquet
`-- [673M]  parquet2
    |-- [   0]  _SUCCESS
    |-- [135M]  part-00000-0ddad3bd-fd52-493b-aabe-7d3f1d9a9861-c000.snappy.parquet
    |-- [135M]  part-00001-0ddad3bd-fd52-493b-aabe-7d3f1d9a9861-c000.snappy.parquet
    |-- [135M]  part-00002-0ddad3bd-fd52-493b-aabe-7d3f1d9a9861-c000.snappy.parquet
    |-- [134M]  part-00003-0ddad3bd-fd52-493b-aabe-7d3f1d9a9861-c000.snappy.parquet
    `-- [134M]  part-00004-0ddad3bd-fd52-493b-aabe-7d3f1d9a9861-c000.snappy.parquet
```

Log includes something like 

```
24/04/19 15:32:50 WARN RssShuffleWriter: RssShuffle start write taskAttemptId data8
24/04/19 15:32:50 WARN RssShuffleWriter: RssShuffle start write taskAttemptId data9
24/04/19 15:33:39 WARN RssShuffleWriter: RssShuffle start write taskAttemptId data10
24/04/19 15:33:43 WARN RssShuffleWriter: RssShuffle start write taskAttemptId data11
24/04/19 15:34:31 WARN RssShuffleWriter: RssShuffle start write taskAttemptId data12
24/04/19 15:34:38 WARN RssShuffleWriter: RssShuffle start write taskAttemptId data13
```

So I assume uniffle was successfully enabled in my test.

**Comment by weiting-chen** [comment]
Close #5121
