### ISSUE TITLE
[VL]java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by RaoZhiRou-Z** [apache/incubator-gluten#5508]
### Backend

VL (Velox)

### Bug description

backend:velox

errors:
    24/04/23 21:27:46 ERROR Executor: Exception in task 242.0 in stage 1.0 (TID 338)
java.lang.UnsupportedOperationException
	at io.glutenproject.vectorized.ColumnarBatchSerializerInstance.serializeStream(ColumnarBatchSerializer.scala:241)
	at org.apache.spark.shuffle.ShufflePartitionPairsWriter.open(ShufflePartitionPairsWriter.scala:76)
	at org.apache.spark.shuffle.ShufflePartitionPairsWriter.write(ShufflePartitionPairsWriter.scala:59)
	at org.apache.spark.util.collection.WritablePartitionedIterator.writeNext(WritablePartitionedPairCollection.scala:83)
	at org.apache.spark.util.collection.ExternalSorter.$anonfun$writePartitionedMapOutput$1(ExternalSorter.scala:767)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1535)
	at org.apache.spark.util.collection.ExternalSorter.writePartitionedMapOutput(ExternalSorter.scala:770)
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:70)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:552)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1535)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:555)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### Spark version

Spark-3.3.x

### Spark configurations

spark.driver.userClassPathFirst         true
spark.executor.userClassPathFirst       true
spark.executor.extraClassPath     ./gluten-velox-bundle-spark3.3_2.12-1.1.1.jar
spark.driver.extraClassPath       /home/work/gluten-velox-bundle-spark3.3_2.12-1.1.1.jar
spark.master yarn
spark.submit.deployMode client

**Comment by RaoZhiRou-Z** [comment]
velox config:
  spark.shuffle.manager org.apache.spark.shuffle.sort.ColumnarShuffleManager
  spark.memory.offHeap.enabled true
  spark.memory.offHeap.size 23G
  spark.plugins io.glutenproject.GlutenPlugin
  spark.gluten.sql.columnar.filescan  false
  spark.gluten.sql.native.writer.enabled  false
  spark.gluten.sql.columnar.batchscan true
  spark.gluten.sql.columnar.hivetablescan false

**Comment by acvictor** [comment]
@RaoZhiRou-Z can you please share a repro?
