### ISSUE TITLE
Operator::getOutput failed for [operator: ValueStream, plan node ID: 0]:IOError: ZSTD decompression failed: Unknown frame descriptor

### ISSUE THREAD

**Issue by boneanxs** [apache/incubator-gluten#5736]
### Backend

VL (Velox)

### Bug description

Meet this error when running with velox backend:

```java
Reason: Operator::getOutput failed for [operator: ValueStream, plan node ID: 0]: Error during calling Java code from native code: org.apache.gluten.exception.GlutenException: java.lang.RuntimeException: IOError: ZSTD decompression failed: Unknown frame descriptor
	at org.apache.gluten.vectorized.GeneralOutIterator.next(GeneralOutIterator.java:48)
	at org.apache.gluten.vectorized.ColumnarBatchSerializerInstance$TaskDeserializationStream.liftedTree1$1(ColumnarBatchSerializer.scala:176)
	at org.apache.gluten.vectorized.ColumnarBatchSerializerInstance$TaskDeserializationStream.readValue(ColumnarBatchSerializer.scala:175)
	at org.apache.spark.serializer.DeserializationStream$$anon$2.getNext(Serializer.scala:188)
	at org.apache.spark.serializer.DeserializationStream$$anon$2.getNext(Serializer.scala:185)
	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:73)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.util.CompletionIterator.hasNext(CompletionIterator.scala:31)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:32)
	at org.apache.gluten.vectorized.GeneralInIterator.hasNext(GeneralInIterator.java:31)
	at org.apache.gluten.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
	at org.apache.gluten.vectorized.ColumnarBatchOutIterator.hasNextInternal(ColumnarBatchOutIterator.java:65)
	at org.apache.gluten.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:37)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:45)
	at org.apache.gluten.utils.IteratorCompleter.hasNext(Iterators.scala:69)
	at org.apache.gluten.utils.PayloadCloser.hasNext(Iterators.scala:35)
	at org.apache.gluten.utils.PipelineTimeAccumulator.hasNext(Iterators.scala:98)
	at scala.collection.Iterator.isEmpty(Iterator.scala:387)
	at scala.collection.Iterator.isEmpty$(Iterator.scala:387)
	at org.apache.gluten.utils.PipelineTimeAccumulator.isEmpty(Iterators.scala:88)
	at org.apache.gluten.execution.VeloxColumnarToRowExec$.toRowIterator(VeloxColumnarToRowExec.scala:119)
	at org.apache.gluten.execution.VeloxColumnarToRowExec.$anonfun$doExecuteInternal$1(VeloxColumnarToRowExec.scala:83)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:863)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:863)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.gluten.execution.ColumnarInputRDDsWrapper.$anonfun$getIterators$1(WholeStageTransformer.scala:441)
	at scala.collection.immutable.List.flatMap(List.scala:366)
	at org.apache.gluten.execution.ColumnarInputRDDsWrapper.getIterators(WholeStageTransformer.scala:432)
	at org.apache.gluten.execution.WholeStageZippedPartitionsRDD.$anonfun$compute$1(WholeStageZippedPartitionsRDD.scala:48)
	at org.apache.gluten.utils.Arm$.withResource(Arm.scala:25)
	at org.apache.gluten.metrics.GlutenTimeMetric$.millis(GlutenTimeMetric.scala:37)
	at org.apache.gluten.execution.WholeStageZippedPartitionsRDD.compute(WholeStageZippedPartitionsRDD.scala:46)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1532)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: IOError: ZSTD decompression failed: Unknown frame descriptor
	at org.apache.gluten.vectorized.ColumnarBatchOutIterator.nativeNext(Native Method)
	at org.apache.gluten.vectorized.ColumnarBatchOutIterator.nextInternal(ColumnarBatchOutIterator.java:70)
	at org.apache.gluten.vectorized.GeneralOutIterator.next(GeneralOutIterator.java:46)
	... 57 more

Retriable: False
Function: runInternal
File: /velox/velox/exec/Driver.cpp
Line: 579
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKSsEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE.cold
# 4  _ZN8facebook5velox4exec6Driver4nextERSt10shared_ptrINS1_13BlockingStateEE
# 5  _ZN8facebook5velox4exec4Task4nextEPN5folly10SemiFutureINS3_4UnitEEE
# 6  _ZN6gluten24WholeStageResultIterator4nextEv
# 7  Java_org_apache_gluten_vectorized_ColumnarBatchOutIterator_nativeHasNext
# 8  0x00007f0145165e70

	at org.apache.gluten.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
	at org.apache.gluten.vectorized.ColumnarBatchOutIterator.hasNextInternal(ColumnarBatchOutIterator.java:65)
	at org.apache.gluten.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:37)
	... 42 more
```

The related DAG graph is:
![Screenshot 2024-05-14 at 11 29 46](https://github.com/apache/incubator-gluten/assets/10115332/941745a5-7742-4080-9b25-6016415b8fec)

### Spark version

Spark-3.2.x

**Comment by zhouyuan** [comment]
@zhztheplayer is this related with some bugs on c2r case?

**Comment by boneanxs** [comment]
> [@zhztheplayer](https://github.com/zhztheplayer) is this related with some bugs on c2r case?

Still meet this error occasionally, @zhztheplayer do you have any clue to investigate?

**Comment by zhztheplayer** [comment]
Looking like something wrong with shuffle read... The error message doesn't reveal the stack of the root cause.

CC @marin-ma in case you have any insights.

**Comment by marin-ma** [comment]
@boneanxs Are you seeing this issue with the main branch? Could you share the configurations related to shuffle?

**Comment by boneanxs** [comment]
We cherry-picked several shuffle-related PRs but missed this one: https://github.com/apache/incubator-gluten/pull/10208/files
.
After including it, the issue was resolved.

Thanks!

**Comment by jianzhenwu** [comment]
hi @marin-ma  We meet this issue again. I printed out the buffers for the shuffle writer and reader. 
The data written by RssPartitionWriter is 
```
E20260106 12:07:02.147404 3830552 RssPartitionWriter.cc:110] [ShuffleWriteDump] partition=0, size=144
E20260106 12:07:02.147465 3830552 RssPartitionWriter.cc:112] [ShuffleWriteDump] HEX:   28 b5 2f fd 00 48 3d 04 00 e4 06 60 00 00 00 04 00 90 a4 eb c9 70 03
``` 

The data read in by ShuffleReader is 
```
E20260106 12:11:19.396942 3970403 Utils.h:426] input_len=6865, compressed_size=6865, compressed_pos=0
E20260106 12:11:19.397058 3970403 Utils.h:429] output_len=1048576
E20260106 12:11:19.397078 3970403 Utils.h:438] input[0..63]: 5a 53 54 44 42 6c 6f 63 6b 10 90 00 00 00 90 00 00 00 62 47 d1 7d 28 b5 2f fd 00 48 3d 04 00 e4 06 60 00 00 00 04 00 90 a4 eb c9 70 03
```
I noticed that it added `5a 53 54 44 42 6c 6f 63 6b 10 90 00 00 00 90 00 00 00 62 47 d1 7d` (which means ZSTDBlock...) to the beginning of the data.

**Comment by jianzhenwu** [comment]
I suspect it's related to this code, because after I removed this code like in this PR, the problem disappeared.
https://github.com/apache/incubator-gluten/commit/6b6b08b1ea183a72d8fd9e82db0afc1214f5d196
