### ISSUE TITLE
[CH] Crash on gluten exit

### ISSUE THREAD

**Issue by zhanglistar** [apache/incubator-gluten#5741]
### Backend

CH (ClickHouse)

### Bug description

<img width="1231" alt="image" src="https://github.com/apache/incubator-gluten/assets/985418/3a5353ce-b82a-44f5-b26b-178fde3943a5">

But, when I gdb the core, get, 
```
BFD: Warning: /data/corefiles/core.VM Thread.78310.1715039755 is truncated: expected core file size >= 1950076928, found: 1391566848.
```

The core is not complete to trace it, need to dig why.

We first found the core on occur 2024.2.12.

### Spark version

Spark-3.3.x

**Comment by zhanglistar** [comment]
ulimit -a
```
yarn@hello-dn119:/data/corefiles$ ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1030220
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1000000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 65536
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
Not the limit problem.

**Comment by zhanglistar** [comment]
This `yarn.nodemanager.sleep-delay-before-sigkill.ms` parameter of yarn cause this.

**Comment by zhanglistar** [comment]
(gdb) bt
#0  0x00007fda35788428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007fda3578a02a in __GI_abort () at abort.c:89
#2  0x00007fda33e8fc15 in __gnu_cxx::__verbose_terminate_handler() ()
   from /data7/hadoop/yarn/local/filecache/187072/jdk-8u391-linux-x64.tar.gz/jdk1.8.0_391/jre/lib/amd64/server/libjvm.so
#3  0x00007fda33e8de36 in __cxxabiv1::__terminate(void (*)()) ()
   from /data7/hadoop/yarn/local/filecache/187072/jdk-8u391-linux-x64.tar.gz/jdk1.8.0_391/jre/lib/amd64/server/libjvm.so
#4  0x00007fda33e8de81 in std::terminate() ()
   from /data7/hadoop/yarn/local/filecache/187072/jdk-8u391-linux-x64.tar.gz/jdk1.8.0_391/jre/lib/amd64/server/libjvm.so
#5  0x00007fda33e841cf in __cxa_pure_virtual ()
   from /data7/hadoop/yarn/local/filecache/187072/jdk-8u391-linux-x64.tar.gz/jdk1.8.0_391/jre/lib/amd64/server/libjvm.so
#6  0x00007fda33ca76b0 in outputStream::print_cr(char const*, ...) ()
   from /data7/hadoop/yarn/local/filecache/187072/jdk-8u391-linux-x64.tar.gz/jdk1.8.0_391/jre/lib/amd64/server/libjvm.so
#7  0x00007fda33e5d323 in VMError::report(outputStream*) ()
   from /data7/hadoop/yarn/local/filecache/187072/jdk-8u391-linux-x64.tar.gz/jdk1.8.0_391/jre/lib/amd64/server/libjvm.so
#8  0x00007fda33e5ef1f in VMError::report_and_die() ()
   from /data7/hadoop/yarn/local/filecache/187072/jdk-8u391-linux-x64.tar.gz/jdk1.8.0_391/jre/lib/amd64/server/libjvm.so
#9  0x00007fda33ca04e5 in JVM_handle_linux_signal ()
   from /data7/hadoop/yarn/local/filecache/187072/jdk-8u391-linux-x64.tar.gz/jdk1.8.0_391/jre/lib/amd64/server/libjvm.so
#10 0x00007fda33c92f48 in signalHandler(int, siginfo*, void*) ()
   from /data7/hadoop/yarn/local/filecache/187072/jdk-8u391-linux-x64.tar.gz/jdk1.8.0_391/jre/lib/amd64/server/libjvm.so
#11 <signal handler called>
#12 0x00007fda48510f2a in Poco::NotificationQueue::dispatch(Poco::NotificationCenter&) () from /home/yarn/libch.so
#13 0x0000000000000000 in ?? ()

**Comment by zhanglistar** [comment]
https://github.com/apache/incubator-gluten/pull/5762
