### ISSUE TITLE
[CH] Crash on exit with Poco exception

### ISSUE THREAD

**Issue by zhanglistar** [apache/incubator-gluten#5744]
### Backend

CH (ClickHouse)

### Bug description

Log is:
```
2024/05/14 16:27:30,975 INFO [dispatcher-Executor] JniLibLoader: Library /data9/hadoop/yarn/local/usercache/xumingyong/appcache/application_1710462985812_739851/container_e57_1710462985812_739851_01_000015/./libch.so has been loaded using path-loading method
2024-05-14 16:27:31.236 <Information> ClickHouseBackend: Init environment variables.
2024-05-14 16:27:31.238 <Debug> CHUtil: Set settings from config key:spark.gluten.sql.columnar.backend.ch.runtime_config.local_engine.settings.log_processors_profiles value:true
2024-05-14 16:27:31.238 <Debug> CHUtil: Set settings key:spark.gluten.sql.columnar.backend.ch.runtime_settings.input_format_orc_row_batch_size value:10000
2024-05-14 16:27:31.238 <Debug> CHUtil: Set settings key:spark.gluten.sql.columnar.backend.ch.runtime_settings.join_algorithm value:grace_hash
2024-05-14 16:27:31.239 <Debug> CHUtil: Set settings key:spark.gluten.sql.columnar.backend.ch.runtime_settings.max_block_size value:8192
2024-05-14 16:27:31.239 <Debug> CHUtil: Set settings key:spark.gluten.sql.columnar.backend.ch.runtime_settings.max_bytes_before_external_group_by value:1610612736
2024-05-14 16:27:31.239 <Debug> CHUtil: Set settings key:spark.gluten.sql.columnar.backend.ch.runtime_settings.max_bytes_before_external_sort value:1073741824
2024-05-14 16:27:31.239 <Debug> CHUtil: Set settings key:spark.gluten.sql.columnar.backend.ch.runtime_settings.max_bytes_in_join value:1073741824
2024-05-14 16:27:31.239 <Debug> CHUtil: Set settings key:spark.gluten.sql.columnar.backend.ch.runtime_settings.max_memory_usage value:3221225472
2024-05-14 16:27:31.239 <Debug> CHUtil: Set settings key:spark.gluten.sql.columnar.backend.ch.runtime_settings.max_threads value:1
2024-05-14 16:27:31.239 <Debug> CHUtil: Set settings key:spark.gluten.sql.columnar.backend.ch.runtime_settings.output_format_orc_compression_method value:snappy
2024-05-14 16:27:31.239 <Debug> CHUtil: Set settings key:spark.gluten.sql.columnar.backend.ch.runtime_settings.query_plan_enable_optimizations value:false
2024-05-14 16:27:31.239 <Debug> CHUtil: Set settings key:spark.gluten.sql.columnar.backend.ch.runtime_settings.short_circuit_function_evaluation value:force_enable
2024-05-14 16:27:31.239 <Information> ClickHouseBackend: Init settings.
2024-05-14 16:27:31.239 <Debug> Context: Setting up /data9/hadoop/yarn/local/usercache/xumingyong/appcache/application_1710462985812_739851/container_e57_1710462985812_739851_01_000015/tmp/libch/ to store temporary data in it
2024-05-14 16:27:31.239 <Information> ClickHouseBackend: Init shared context and global context.
2024-05-14 16:27:31.239 <Information> ClickHouseBackend: Apply configuration and setting for global context.
2024-05-14 16:27:31.239 <Warning> SignalHandler: LD_PRELOAD is not set, SignalHandler is disabled
2024-05-14 16:27:31.239 <Information> ClickHouseBackend: Register read buffer builders.
2024-05-14 16:27:31.239 <Information> ClickHouseBackend: Register relation parsers.
2024-05-14 16:27:31.248 <Information> ClickHouseBackend: Register all functions.
2024-05-14 16:27:31.248 <Information> ClickHouseBackend: Register all factories.
2024-05-14 16:27:31.248 <Information> ClickHouseBackend: Init compiled expressions cache factory.
2024/05/14 16:27:31,269 INFO [dispatcher-Executor] ExecutorPluginContainer: Initialized executor component for plugin org.apache.gluten.GlutenPlugin.
2024/05/14 16:27:31,272 INFO [dispatcher-GlutenExecutorEndpoint] GlutenExecutorEndpoint: Initialized GlutenExecutorEndpoint.
2024/05/14 16:27:40,979 ERROR [SIGTERM handler] CoarseGrainedExecutorBackend: RECEIVED SIGNAL TERM
2024/05/14 16:27:41,080 INFO [shutdown-hook-0] MemoryStore: MemoryStore cleared
2024/05/14 16:27:41,081 INFO [shutdown-hook-0] BlockManager: BlockManager stopped
2024/05/14 16:27:41,098 INFO [shutdown-hook-0] ShutdownHookManager: Shutdown hook called
libc++abi: terminating due to uncaught exception of type Poco::SystemException: System exception
```

### Spark version

Spark-3.3.x

**Comment by zhanglistar** [comment]
(gdb) bt
#0  0x00007fab0a920428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007fab0a92202a in __GI_abort () at abort.c:89
#2  0x00007fab1e28f346 in abort_message () from /home/yarn/libch.so
#3  0x00007fab1e28f56d in demangling_terminate_handler() ()
   from /home/yarn/libch.so
#4  0x00007fab1e28f423 in std::__terminate(void (*)()) ()
   from /home/yarn/libch.so
#5  0x00007fab1e28eb16 in __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) () from /home/yarn/libch.so
#6  0x00007fab1e28ea8f in __cxa_throw () from /home/yarn/libch.so
#7  0x00007fab118b7a4c in Poco::ScopedLock<Poco::FastMutex>::ScopedLock(Poco::FastMutex&) () from /home/yarn/libch.so
#8  0x00007fab1d8ab9f9 in Poco::ErrorHandler::handle(Poco::Exception const&) () from /home/yarn/libch.so
#9  0x00007fab1d8aa249 in Poco::ThreadImpl::runnableEntry(void*) ()
   from /home/yarn/libch.so
#10 0x00007fab0b0d96ba in start_thread (arg=0x7faac877c700)
    at pthread_create.c:333
#11 0x00007fab0a9f241d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
