### ISSUE TITLE
[CH] Invalid timezone exception while set GMT+/GMT- timezone

### ISSUE THREAD

**Issue by KevinyhZou** [apache/incubator-gluten#5974]
### Backend

CH (ClickHouse)

### Bug description

if set spark.sql.session.timeZone = GMT+8 or GMT-8 in spark config, then the exception while be throw as below
```
Exception in thread "main" org.apache.gluten.exception.GlutenException: Invalid time zone: GMT+8
0. Poco::Exception::Exception(String const&, int) @ 0x0000000013148a39
1. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000afe94bb
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000060ba1ac
3. DB::Exception::Exception<String const&>(int, FormatStringHelperImpl<std::type_identity<String const&>::type>, String const&) @ 0x00000000061d4c0b
4. DB::SettingFieldTimezone::validateTimezone(String const&) @ 0x000000000e3e73f5
5. DB::SettingFieldTimezone::operator=(std::basic_string_view<char, std::char_traits<char>>) @ 0x000000000e39db1f
6. DB::BaseSettings<DB::SettingsTraits>::set(std::basic_string_view<char, std::char_traits<char>>, DB::Field const&) @ 0x00000000078bd1df
7. DB::Settings::set(std::basic_string_view<char, std::char_traits<char>>, DB::Field const&) @ 0x000000000e2990df
8. local_engine::BackendInitializerUtil::initSettings(std::map<String, String, std::less<String>, std::allocator<std::pair<String const, String>>>&, DB::Settings&) @ 0x000000000b55d766
9. local_engine::BackendInitializerUtil::init(String*) @ 0x000000000b562267
10. Java_org_apache_gluten_vectorized_ExpressionEvaluatorJniWrapper_nativeInitNative @ 0x000000000609d420

        at org.apache.gluten.vectorized.ExpressionEvaluatorJniWrapper.nativeInitNative(Native Method)
        at org.apache.gluten.vectorized.CHNativeExpressionEvaluator.initNative(CHNativeExpressionEvaluator.java:61)
        at org.apache.gluten.backendsapi.clickhouse.CHListenerApi.initialize(CHListenerApi.scala:97)
        at org.apache.gluten.backendsapi.clickhouse.CHListenerApi.onDriverStart(CHListenerApi.scala:44)
        at org.apache.gluten.GlutenDriverPlugin.init(GlutenPlugin.scala:75)
        at org.apache.spark.internal.plugin.DriverPluginContainer.$anonfun$driverPlugins$1(PluginContainer.scala:53)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
        at org.apache.spark.internal.plugin.DriverPluginContainer.<init>(PluginContainer.scala:46)
        at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:210)
        at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:193)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:570)
```

as GMT+/GMT- is not supported in clickhouse backend, but Etc/GMT+, Etc/GMT- is supported.

### Spark version

Spark-3.3.x

**Comment by ditgittube** [comment]
@KevinyhZou Which pr resolve this issue?
