### ISSUE TITLE
[CH] unstable CI due to Unload JNI before Task ends

### ISSUE THREAD

**Issue by baibaichen** [apache/incubator-gluten#6272]
### Problem description

we often see such core dumps:
``` 
[2024-06-28T14:23:01.495Z] All tests passed.
[2024-06-28T14:23:01.495Z] 2024-06-28 07:23:01.364 <Fatal> SignalListener: ########################################
[2024-06-28T14:23:01.495Z] 2024-06-28 07:23:01.364 <Fatal> SignalListener: (version 24.7.1.1, build id: , git hash: getGitHash()) (from thread 80057) (query_id: 06774009-6632-4d66-bbd2-bed7829938f4) (query: ) Received signal Segmentation fault (11)
[2024-06-28T14:23:01.495Z] 2024-06-28 07:23:01.364 <Fatal> SignalListener: Address: NULL pointer. Access: read. Address not mapped to object.
[2024-06-28T14:23:01.495Z] 2024-06-28 07:23:01.409 <Fatal> SignalListener: 0. /home/jenkins/agent/workspace/gluten/gluten-ci/gluten/cpp-ch/build/../local-engine/Common/GlutenSignalHandler.cpp:0: signalHandler(int, siginfo_t*, void*) @ 0x000000000b7e48fd
[2024-06-28T14:23:01.495Z] 2024-06-28 07:23:01.409 <Fatal> SignalListener: 1. os::Linux::chained_handler(int, siginfo*, void*) @ 0x0000000000933307
[2024-06-28T14:23:01.495Z] 2024-06-28 07:23:01.409 <Fatal> SignalListener: 2. JVM_handle_linux_signal @ 0x000000000093a8a5
[2024-06-28T14:23:01.495Z] 2024-06-28 07:23:01.409 <Fatal> SignalListener: 3. signalHandler(int, siginfo*, void*) @ 0x000000000092fae3
[2024-06-28T14:23:01.496Z] 2024-06-28 07:23:01.409 <Fatal> SignalListener: 4. ? @ 0x0000000000012730
[2024-06-28T14:23:01.496Z] 2024-06-28 07:23:01.409 <Fatal> SignalListener: 5. jni_NewObjectV @ 0x00000000006fbdd0
[2024-06-28T14:23:01.496Z] 2024-06-28 07:23:01.427 <Fatal> SignalListener: 6. /usr/lib/jvm/java-8-openjdk-amd64/include/jni.h:874: JNIEnv_::NewObject(_jclass*, _jmethodID*, ...) @ 0x0000000005fb40c2
[2024-06-28T14:23:01.496Z] 2024-06-28 07:23:01.444 <Fatal> SignalListener: 7. /home/jenkins/agent/workspace/Gluten/gluten-ext-ci/gluten/cpp-ch/build/../local-engine/local_engine_jni.cpp:0: Java_org_apache_gluten_vectorized_BatchIterator_nativeFetchMetrics @ 0x0000000005fb3a9e
[2024-06-28T14:23:01.496Z] 2024-06-28 07:23:01.444 <Fatal> SignalListener: Integrity check of the executable skipped because the reference checksum could not be read.
[2024-06-28T14:23:01.496Z] 2024-06-28 07:23:01.444 <Fatal> SignalListener: Changed settings: log_processors_profiles = true, join_use_nulls = true, max_bytes_before_external_group_by = 536870912, prefer_external_sort_block_bytes = 8388608, max_bytes_before_external_sort = 858993459, max_memory_usage = 1073741824, query_plan_enable_optimizations = false, function_json_value_return_type_allow_nullable = true, function_json_value_return_type_allow_complex = true, input_format_csv_allow_cr_end_of_line = true, input_format_orc_case_insensitive_column_matching = true, input_format_parquet_case_insensitive_column_matching = true, input_format_orc_allow_missing_columns = true, input_format_parquet_allow_missing_columns = true, input_format_csv_trim_whitespaces = false, input_format_orc_skip_columns_with_unsupported_types_in_schema_inference = true, input_format_json_read_bools_as_numbers = false, input_format_json_read_numbers_as_strings = true, date_time_input_format = 'best_effort', output_format_json_quote_64bit_integers = false, output_format_json_quote_denormals = true, output_format_json_escape_forward_slashes = false, output_format_json_skip_null_value_in_named_tuples = true, output_format_parquet_string_as_string = true, output_format_parquet_fixed_string_as_fixed_byte_array = false, output_format_parquet_version = '1.0', output_format_parquet_compression_method = 'snappy', output_format_orc_string_as_string = true, output_format_orc_compression_method = 'snappy', precise_float_parsing = true, input_format_parquet_import_nested = true, input_format_orc_import_nested = true, fs.s3a.use.instance.credentials = 'false', fs.s3a.path.style.access = 'true', fs.s3a.iam.role.session.name = '', fs.s3a.iam.role = '', fs.s3a.connection.ssl.enabled = 'false', fs.s3a.connection.maximum = '15', fs.s3a.retry.limit = '20', spark.sql.decimalOperations.allowPrecisionLoss = true, mergetree.merge_after_insert = true, fs.s3a.secret.key = '', mergetree.insert_without_local_storage = false, fs.s3a.endpoint = 'localhost:9000', fs.s3a.access.key = ''
[2024-06-28T14:23:02.419Z] #
[2024-06-28T14:23:02.419Z] # A fatal error has been detected by the Java Runtime Environment:
[2024-06-28T14:23:02.419Z] #
[2024-06-28T14:23:02.419Z] #  SIGSEGV (0xb) at pc=0x00007efc753e6dcf, pid=45814, tid=0x00007efc2f34c700
[2024-06-28T14:23:02.419Z] #
[2024-06-28T14:23:02.419Z] # JRE version: OpenJDK Runtime Environment (8.0_282-b08) (build 1.8.0_282-b08)
[2024-06-28T14:23:02.419Z] # Java VM: OpenJDK 64-Bit Server VM (25.282-b08 mixed mode linux-amd64 compressed oops)
[2024-06-28T14:23:02.419Z] # Problematic frame:
[2024-06-28T14:23:02.419Z] # V  [libjvm.so+0x6fbdcf]  jni_NewObjectV+0xdf
[2024-06-28T14:23:02.419Z] #
[2024-06-28T14:23:02.419Z] # Core dump written. Default location: /home/jenkins/agent/workspace/Gluten/gluten-ext-ci/gluten/gluten-ut/spark33/core or core.45814
[2024-06-28T14:23:02.419Z] #
[2024-06-28T14:23:02.419Z] # An error report file with more information is saved as:
[2024-06-28T14:23:02.419Z] # /home/jenkins/agent/workspace/Gluten/gluten-ext-ci/gluten/gluten-ut/spark33/hs_err_pid45814.log
[2024-06-28T14:23:02.673Z] #
[2024-06-28T14:23:02.673Z] # If you would like to submit a bug report, please visit:
[2024-06-28T14:23:02.673Z] #   http://bugreport.java.com/bugreport/crash.jsp
```

### System information

No

**Comment by baibaichen** [comment]
I reproduced it locally, and the stack is as follows. It's strange why there are still running tasks when calling the shutdown hook.

When JNI_onUnload is called, subsequent JNI calls are undefined, which causes core dump.

| Thread       | Stack                                                        |
| ------------ | ------------------------------------------------------------ |
| ShutDownhook | ![035bf2dff26be77152b353e1368d242](https://github.com/apache/incubator-gluten/assets/3688732/b8ad8ad6-d7c5-41e4-b2a5-ca12c25d4153) |
| Executor     | ![18ef14f3ff3de43eaa12444f7e0f28e](https://github.com/apache/incubator-gluten/assets/3688732/49e2699f-44d7-444c-8e3d-10ad7b179aac) |

**Comment by baibaichen** [comment]
`Sleep(30)` looks not ok.
![image](https://github.com/apache/incubator-gluten/assets/3688732/60297988-8636-49dd-bef0-3744e51cd3e9)

it cause shutdown hook timeout. see  [here](https://opencicd.kyligence.com/blue/rest/organizations/jenkins/pipelines/gluten/pipelines/gluten-ci/runs/10461/nodes/125/steps/170/log/?start=0) for details

```
[2024-07-02T03:05:24.680Z] 03:05:22.493 WARN org.apache.hadoop.util.ShutdownHookManager: ShutdownHook '$anon$2' timeout, java.util.concurrent.TimeoutException
[2024-07-02T03:05:24.680Z] java.util.concurrent.TimeoutException
[2024-07-02T03:05:24.680Z] 	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
[2024-07-02T03:05:24.680Z] 	at org.apache.hadoop.util.ShutdownHookManager.executeShutdown(ShutdownHookManager.java:124)
[2024-07-02T03:05:24.680Z] 	at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:95)
[2024-07-02T03:05:24.680Z] 03:05:22.493 ERROR org.apache.spark.util.Utils: Uncaught exception in thread shutdown-hook-0
[2024-07-02T03:05:24.680Z] java.lang.RuntimeException: java.lang.InterruptedException: sleep interrupted
[2024-07-02T03:05:24.680Z] 	at org.apache.gluten.vectorized.JniLibLoader.forceUnloadAll(JniLibLoader.java:85)
[2024-07-02T03:05:24.680Z] 	at org.apache.gluten.vectorized.JniLibLoader.lambda$static$0(JniLibLoader.java:67)
[2024-07-02T03:05:24.680Z] 	at scala.Function0.apply$mcV$sp(Function0.scala:39)
[2024-07-02T03:05:24.680Z] 	at org.apache.spark.util.SparkShutdownHook.run(ShutdownHookManager.scala:214)
[2024-07-02T03:05:24.680Z] 	at org.apache.spark.util.SparkShutdownHookManager.$anonfun$runAll$2(ShutdownHookManager.scala:188)
[2024-07-02T03:05:24.680Z] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2024-07-02T03:05:24.680Z] 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2066)
[2024-07-02T03:05:24.680Z] 	at org.apache.spark.util.SparkShutdownHookManager.$anonfun$runAll$1(ShutdownHookManager.scala:188)
[2024-07-02T03:05:24.680Z] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2024-07-02T03:05:24.680Z] 	at scala.util.Try$.apply(Try.scala:213)
[2024-07-02T03:05:24.680Z] 	at org.apache.spark.util.SparkShutdownHookManager.runAll(ShutdownHookManager.scala:188)
[2024-07-02T03:05:24.680Z] 	at org.apache.spark.util.SparkShutdownHookManager$$anon$2.run(ShutdownHookManager.scala:178)
[2024-07-02T03:05:24.680Z] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2024-07-02T03:05:24.680Z] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2024-07-02T03:05:24.680Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2024-07-02T03:05:24.681Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2024-07-02T03:05:24.681Z] 	at java.lang.Thread.run(Thread.java:748)
[2024-07-02T03:05:24.681Z] Caused by: java.lang.InterruptedException: sleep interrupted
[2024-07-02T03:05:24.681Z] 	at java.lang.Thread.sleep(Native Method)
[2024-07-02T03:05:24.681Z] 	at org.apache.gluten.vectorized.JniLibLoader.forceUnloadAll(JniLibLoader.java:83)
[2024-07-02T03:05:24.681Z] 	... 16 more
```
