### ISSUE TITLE
fail to build schema when iceberg partition columns contains timestamptz.

### ISSUE THREAD

**Issue by j7nhai** [apache/incubator-gluten#6509]
### Backend

VL (Velox)

### Bug description

```
Caused by: org.apache.spark.sql.catalyst.parser.ParseException:
DataType timestamptz is not supported.(line 1, pos 0)

== SQL ==
timestamptz
^^^

	at org.apache.spark.sql.errors.QueryParsingErrors$.dataTypeUnsupportedError(QueryParsingErrors.scala:239)
	at org.apache.spark.sql.catalyst.parser.AstBuilder.$anonfun$visitPrimitiveDataType$1(AstBuilder.scala:2692)
	at org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:157)
	at org.apache.spark.sql.catalyst.parser.AstBuilder.visitPrimitiveDataType(AstBuilder.scala:2662)
	at org.apache.spark.sql.catalyst.parser.AstBuilder.visitPrimitiveDataType(AstBuilder.scala:58)
	at org.apache.spark.sql.catalyst.parser.SqlBaseParser$PrimitiveDataTypeContext.accept(SqlBaseParser.java:19246)

```

### Spark version

None

**Comment by j7nhai** [comment]
fix on PR #6508
