### ISSUE TITLE
[VL] window bug !next->isPreviousFree()

### ISSUE THREAD

**Issue by FelixYBW** [apache/incubator-gluten#6546]
### Backend

VL (Velox)

### Bug description

reported by window:

```
24/07/21 16:33:11 WARN [task-result-getter-3] scheduler.TaskSetManager: Lost task 405.0 in stage 11.0 (TID 7781) (monarch-dev-015-20221117-dpp-worker-dev-0a027985.ec2.pin220.com executor 6): org.apache.gluten.exception.GlutenException: org.apache.gluten.exception.GlutenException: Error during calling Java code from native code: org.apache.gluten.exception.GlutenException: org.apache.gluten.exception.GlutenException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Retriable: False
Expression: !next->isPreviousFree()
Context: Operator: Window[2] 2
Function: free
File: /home/binweiyang/gluten/ep/build-velox/build/velox_ep/velox/common/memory/HashStringAllocator.cpp
Line: 486
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorENS1_22CompileTimeEmptyStringEEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  _ZN8facebook5velox19HashStringAllocator4freeEPNS1_6HeaderE
# 4  _ZN8facebook5velox4exec12RowContainer23freeVariableWidthFieldsEN5folly5RangeIPPcEE
# 5  _ZN8facebook5velox4exec12RowContainer19freeRowsExtraMemoryEN5folly5RangeIPPcEEb
# 6  _ZN8facebook5velox4exec12RowContainer9eraseRowsEN5folly5RangeIPPcEE
# 7  _ZN8facebook5velox4exec15WindowPartition15clearOutputRowsEi
# 8  _ZN8facebook5velox4exec6Window25callApplyForPartitionRowsEiiiRKSt10shared_ptrINS0_9RowVectorEE
# 9  _ZN8facebook5velox4exec6Window13callApplyLoopEiRKSt10shared_ptrINS0_9RowVectorEE
# 10 _ZN8facebook5velox4exec6Window9getOutputEv
# 11 _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE
# 12 _ZN8facebook5velox4exec6Driver4nextERSt10shared_ptrINS1_13BlockingStateEE
# 13 _ZN8facebook5velox4exec4Task4nextEPN5folly10SemiFutureINS3_4UnitEEE
# 14 _ZN6gluten24WholeStageResultIterator4nextEv
# 15 Java_org_apache_gluten_vectorized_ColumnarBatchOutIterator_nativeHasNext
# 16 0x00007f43f19f37a8

        at org.apache.gluten.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:39)
        at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:43)
        at org.apache.gluten.utils.iterator.IteratorsV1$InvocationFlowProtection.hasNext(IteratorsV1.scala:159)
        at org.apache.gluten.utils.iterator.IteratorsV1$IteratorCompleter.hasNext(IteratorsV1.scala:71)
        at org.apache.gluten.utils.iterator.IteratorsV1$PayloadCloser.hasNext(IteratorsV1.scala:37)
        at org.apache.gluten.utils.iterator.IteratorsV1$LifeTimeAccumulator.hasNext(IteratorsV1.scala:100)
        at org.apache.gluten.utils.iterator.IteratorsV1$ReadTimeAccumulator.hasNext(IteratorsV1.scala:127)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:31)
        at org.apache.gluten.vectorized.GeneralInIterator.hasNext(GeneralInIterator.java:31)
        at org.apache.gluten.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)

```

### Spark version

Spark-3.2.x

**Comment by FelixYBW** [comment]
Another similar one:
```
24/07/21 15:47:42 WARN [task-result-getter-0] scheduler.TaskSetManager: Lost task 432.0 in stage 7.0 (TID 143962) (monarch-dev-015-20221117-dpp-worker-dev-0a027085.ec2.pin220.com executor 398): org.apache.gluten.exception.GlutenException: org.apache.gluten.exception.GlutenException: Error during calling Java code from native code: org.apache.gluten.exception.GlutenException: org.apache.gluten.exception.GlutenException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: Double free of row
Retriable: False
Expression: !bits::isBitSet(row, freeFlagOffset_)
Context: Operator: Window[2] 2
Function: eraseRows
File: /home/binweiyang/gluten/ep/build-velox/build/velox_ep/velox/exec/RowContainer.cpp
Line: 342
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorEPKcEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  _ZN8facebook5velox4exec12RowContainer9eraseRowsEN5folly5RangeIPPcEE
# 4  _ZN8facebook5velox4exec15WindowPartition15clearOutputRowsEi
# 5  _ZN8facebook5velox4exec6Window25callApplyForPartitionRowsEiiiRKSt10shared_ptrINS0_9RowVectorEE
# 6  _ZN8facebook5velox4exec6Window13callApplyLoopEiRKSt10shared_ptrINS0_9RowVectorEE
# 7  _ZN8facebook5velox4exec6Window9getOutputEv
# 8  _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE
# 9  _ZN8facebook5velox4exec6Driver4nextERSt10shared_ptrINS1_13BlockingStateEE
# 10 _ZN8facebook5velox4exec4Task4nextEPN5folly10SemiFutureINS3_4UnitEEE
# 11 _ZN6gluten24WholeStageResultIterator4nextEv
# 12 Java_org_apache_gluten_vectorized_ColumnarBatchOutIterator_nativeHasNext
# 13 0x00007f8b5a6eef28

        at org.apache.gluten.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:39)
        at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:43)
        at org.apache.gluten.utils.iterator.IteratorsV1$InvocationFlowProtection.hasNext(IteratorsV1.scala:159)
        at org.apache.gluten.utils.iterator.IteratorsV1$IteratorCompleter.hasNext(IteratorsV1.scala:71)
        at org.apache.gluten.utils.iterator.IteratorsV1$PayloadCloser.hasNext(IteratorsV1.scala:37)
        at org.apache.gluten.utils.iterator.IteratorsV1$LifeTimeAccumulator.hasNext(IteratorsV1.scala:100)
        at org.apache.gluten.utils.iterator.IteratorsV1$ReadTimeAccumulator.hasNext(IteratorsV1.scala:127)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:31)
        at org.apache.gluten.vectorized.GeneralInIterator.hasNext(GeneralInIterator.java:31)
        at org.apache.gluten.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
        at org.apache.gluten.vectorized.ColumnarBatchOutIterator.hasNextInternal(ColumnarBatchOutIterator.java:61)
        at org.apache.gluten.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:37)
        at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:43)
        at org.apache.gluten.utils.iterator.IteratorsV1$ReadTimeAccumulator.hasNext(IteratorsV1.scala:127)
        at org.apache.gluten.utils.iterator.IteratorsV1$PayloadCloser.hasNext(IteratorsV1.scala:37)
        at org.apache.gluten.utils.iterator.IteratorsV1$IteratorCompleter.hasNext(IteratorsV1.scala:71)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)

```

**Comment by FelixYBW** [comment]
both are fixed. THank you @JkSelf
