### ISSUE TITLE
[VL] Exception: Node id cannot be found in plan status in branch-1.2

### ISSUE THREAD

**Issue by kecookier** [apache/incubator-gluten#7024]
### Backend

VL (Velox)

### Bug description

Exception:
![image](https://github.com/user-attachments/assets/d729f183-3d3c-4412-b758-495bedabcab9)

```
org.apache.spark.util.TaskCompletionListenerException: Node id cannot be found in plan status.
	at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:150)
	at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:129)
	at org.apache.spark.scheduler.Task.run(Task.scala:150)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:479)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1426)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:482)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

### Spark version

None

**Comment by kecookier** [comment]
sql
```
SELECT p1.*,p2.flag
  FROM (
        SELECT linkid,
               direction,
               hot,
               hot*1000/link_length AS avg_hot,
               link_length,
               geometry,
               adcode
          FROM (
                SELECT a.linkid,
                       direction,
                       adcode,
                       count(DISTINCT a.userid) AS hot
                  FROM (
                        SELECT s_linkid AS linkid,
                               direction,
                               substr(town_adcode,1,6) adcode,
                               userid
                          FROM leftTableA
                         WHERE dt='20240819'
                           AND s_linkid=lag_s_linkid
                           AND speed<10
                     UNION ALL SELECT linkid,
                               direction,
                               substr(town_adcode,1,6) adcode,
                               userid
                          FROM rightTableB
                         WHERE dt='20240819'
                           AND ((link_con>2 AND LENGTH/dis<=1.5) OR link_con=2)
                           AND link_con<=5
                           AND dis>15
                           AND speed<10
                       )a
                  JOIN (
                        SELECT *
                          FROM (
                                SELECT userid,
                                       linkid,
                                       max(unix_timestamp(TIME,'yyyy-MM-dd HH:mm:ss')) AS max_t,
                                       min(unix_timestamp(TIME,'yyyy-MM-dd HH:mm:ss')) AS min_t,
                                       max(unix_timestamp(TIME,'yyyy-MM-dd HH:mm:ss'))-min(unix_timestamp(TIME,'yyyy-MM-dd HH:mm:ss')) AS time_dis,
                                       count(DISTINCT direction) AS type_con,
                                       count(1) con
                                  FROM (
                                        SELECT s_linkid AS linkid,
                                               direction,
                                               TIME,
                                               userid
                                          FROM leftTableA
                                         WHERE dt='20240819'
                                           AND s_linkid=lag_s_linkid
                                           AND speed<10
                                     UNION ALL SELECT linkid,
                                               direction,
                                               TIME,
                                               userid
                                          FROM rightTableB
                                         WHERE dt='20240819'
                                           AND ((link_con>2 AND LENGTH/dis<=1.5) OR link_con=2)
                                           AND link_con<=5
                                           AND dis>15
                                           AND speed<10
                                       )a
                                 GROUP BY userid,
                                          linkid
                               )
                         WHERE !(type_con>1 AND time_dis<600)
                       )b
                    ON a.userid=b.userid
                   AND a.linkid=b.linkid
                 GROUP BY a.linkid,
                          direction,
                          adcode
               )t1
          JOIN (
                SELECT *
                  FROM tableC
                 WHERE dt=(
                        SELECT max(dt)
                          FROM tableC
                         WHERE dt LIKE "%.%00p00"
                       )
               )t2
            ON t1.linkid=cast(t2.link_id AS string)
       )p1
  JOIN (SELECT link_id,flag
  FROM (
        SELECT *,
               LinkFilter(link_type,link_tag,link_level) AS flag
          FROM tabled
         WHERE dt=(
                SELECT max(dt)
                  FROM tabled
                 WHERE product_dt<='20240819'
               )
           )t
       )p2
    ON p1.linkid=p2.link_id
```

**Comment by kecookier** [comment]
DAG of failed stage
![image](https://github.com/user-attachments/assets/3aae8c8f-f748-4a35-8f00-a2497aead3b0)
![image](https://github.com/user-attachments/assets/4e4c0fe7-73b0-49ae-a11e-181ceccd8a60)
![image](https://github.com/user-attachments/assets/33076f44-a9d0-40a5-bc20-95e9b3a4b0fc)
