### ISSUE TITLE
[VL]Operator::getOutput failed for [operator: TableScan, plan node ID: 0]: Columns not found in hive table: #user_id

### ISSUE THREAD

**Issue by winfys** [apache/incubator-gluten#7081]
### Backend

VL (Velox)

### Bug description

```
CREATE TABLE .dws_user_tags_full (
  `#user_id` STRING,
  register_time BIGINT,
  channel_id STRING,
  app_channel_id STRING,
  last_login_time BIGINT,
  total_charge DOUBLE,
  rolenumber DOUBLE,
  servernumber DOUBLE,
  role_key STRING,
  role_id STRING,
  device_uuid STRING,
  platform STRING,
  dt STRING)
USING parquet
PARTITIONED BY (dt)
LOCATION '/user/hive/warehouse/dws.db/dws_user_tags_full'
```
query sql:
“select  \`#user_id\` from dws.dws_user_tags_full  limit 10;”

```
Caused by: io.glutenproject.exception.GlutenException: java.lang.RuntimeException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: Operator::getOutput failed for [operator: TableScan, plan node ID: 0]: Columns not found in hive table: #user_id
Retriable: False
Function: runInternal
File: /root/src/oap-project/gluten/ep/build-velox/build/velox_ep/velox/exec/Driver.cpp
Line: 581
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKSsEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE.cold
# 4  _ZN8facebook5velox4exec6Driver4nextERSt10shared_ptrINS1_13BlockingStateEE
# 5  _ZN8facebook5velox4exec4Task4nextEPN5folly10SemiFutureINS3_4UnitEEE
# 6  _ZN6gluten24WholeStageResultIterator4nextEv
# 7  Java_io_glutenproject_vectorized_ColumnarBatchOutIterator_nativeHasNext
# 8  0x00007fe461018427

        at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:39)
        at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:45)
        at io.glutenproject.utils.InvocationFlowProtection.hasNext(Iterators.scala:135)
        at io.glutenproject.utils.IteratorCompleter.hasNext(Iterators.scala:69)
        at io.glutenproject.utils.PayloadCloser.hasNext(Iterators.scala:35)
        at io.glutenproject.utils.PipelineTimeAccumulator.hasNext(Iterators.scala:98)
        at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
        at scala.collection.Iterator.isEmpty(Iterator.scala:387)
        at scala.collection.Iterator.isEmpty$(Iterator.scala:387)
        at org.apache.spark.InterruptibleIterator.isEmpty(InterruptibleIterator.scala:28)
        at io.glutenproject.execution.VeloxColumnarToRowExec$.toRowIterator(VeloxColumnarToRowExec.scala:116)
        at io.glutenproject.execution.VeloxColumnarToRowExec.$anonfun$doExecuteInternal$1(VeloxColumnarToRowExec.scala:80)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:855)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:855)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:136)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
        ... 3 more

```

### Spark version

Spark-3.3.x

### Spark configurations

spark.memory.offHeap.enabled true
spark.memory.offHeap.size 10G
spark.sql.join.preferSortMergeJoin false
#spark.plugins org.apache.gluten.GlutenPlugin
spark.plugins io.glutenproject.GlutenPlugin
#spark.sql.sources.useV1SourceList avro
spark.shuffle.manager org.apache.spark.shuffle.sort.ColumnarShuffleManager
spark.gluten.enabled true
spark.gluten.memory.isolation false
spark.gluten.ras.enabled false
spark.gluten.sql.columnar.maxBatchSize 4096
spark.gluten.sql.columnar.scanOnly false
#spark.driver.extraClassPath /opt/apps/spark-3.3.1-bin-hadoop3/jars/gluten-velox-bundle-spark3.3_2.12-1.1.1.jar
#spark.executor.extraClassPath /opt/apps/spark-3.3.1-bin-hadoop3/jars/gluten-velox-bundle-spark3.3_2.12-1.1.1.jar

**Comment by Yohahaha** [comment]
cannot repro the issue, could you post parquet schema?

**Comment by winfys** [comment]
> cannot repro the issue, could you post parquet schema?

```
File path:  part-00001-0189d218-8693-4303-bd7c-00ac78033685.c000.snappy.parquet
Created by: parquet-mr version 1.12.2 (build 77e30c8093386ec52c3cfa6c34b7ef3321322c94)
Properties:
                  org.apache.spark.timeZone: Asia/Shanghai
                   org.apache.spark.version: 3.3.1
  org.apache.spark.sql.parquet.row.metadata: {"type":"struct","fields":[{"name":"#user_id","type":"string","nullable":true,"metadata":{}},{"name":"register_time","type":"long","nullable":true,"metadata":{}},{"name":"channel_id","type":"string","nullable":true,"metadata":{}},{"name":"app_channel_id","type":"string","nullable":true,"metadata":{}},{"name":"last_login_time","type":"long","nullable":true,"metadata":{}},{"name":"total_charge","type":"double","nullable":true,"metadata":{}},{"name":"rolenumber","type":"double","nullable":true,"metadata":{}},{"name":"servernumber","type":"double","nullable":true,"metadata":{}},{"name":"role_key","type":"string","nullable":true,"metadata":{}},{"name":"role_id","type":"string","nullable":true,"metadata":{}},{"name":"device_uuid","type":"string","nullable":true,"metadata":{}},{"name":"platform","type":"string","nullable":true,"metadata":{}}]}
            org.apache.spark.legacyDateTime: 
Schema:
message spark_schema {
  optional binary #user_id (STRING);
  optional int64 register_time;
  optional binary channel_id (STRING);
  optional binary app_channel_id (STRING);
  optional int64 last_login_time;
  optional double total_charge;
  optional double rolenumber;
  optional double servernumber;
  optional binary role_key (STRING);
  optional binary role_id (STRING);
  optional binary device_uuid (STRING);
  optional binary platform (STRING);
}


Row group 0:  count: 348613  41.34 B records  start: 4  total(compressed): 13.743 MB total(uncompressed):24.625 MB 
--------------------------------------------------------------------------------
                 type      encodings count     avg size   nulls   min / max
#user_id         BINARY    S   _     348613    8.73 B     0       "00004510726fafb4" / "zy6ihih975misf7o"
register_time    INT64     S   _     348613    4.92 B     0       "1631777450" / "1689091108"
channel_id       BINARY    S _ R     348613    0.36 B     0       "1" / "94"
app_channel_id   BINARY    S _ R     348613    0.31 B     0       "" / "填写cpsID，若无可不填"
last_login_time  INT64     S   _     348613    5.15 B     0       "1631843161" / "1689091153"
total_charge     DOUBLE    S _ R     348613    0.25 B     315355  "-0.0" / "257773.0"
rolenumber       DOUBLE    S _ R     348613    0.13 B     0       "1.0" / "42.0"
servernumber     DOUBLE    S _ R     348613    0.13 B     0       "1.0" / "42.0"
role_key         BINARY    S   _     348613    7.07 B     0       "10000_400008" / "20103_765248"
role_id          BINARY    S   _     348613    5.48 B     0       "400006" / "788932"
device_uuid      BINARY    S   _     348613    8.81 B     5       "0" / "99999"
platform         BINARY    S _ R     348613    0.00 B     0       "SERVER" / "SERVER"
```



Except for the `#user_id` field, it is normal for me to query other fields

**Comment by Yohahaha** [comment]
> #spark.driver.extraClassPath /opt/apps/spark-3.3.1-bin-hadoop3/jars/gluten-velox-bundle-spark3.3_2.12-1.1.1.jar
#spark.executor.extraClassPath /opt/apps/spark-3.3.1-bin-hadoop3/jars/gluten-velox-bundle-spark3.3_2.12-1.1.1.jar

would you try with 1.2.0? https://github.com/apache/incubator-gluten/releases/tag/v1.2.0

I am still unable to reproduce this issue.

**Comment by winfys** [comment]
> > #spark.driver.extraClassPath /opt/apps/spark-3.3.1-bin-hadoop3/jars/gluten-velox-bundle-spark3.3_2.12-1.1.1.jar
> > #spark.executor.extraClassPath /opt/apps/spark-3.3.1-bin-hadoop3/jars/gluten-velox-bundle-spark3.3_2.12-1.1.1.jar
> 
> would you try with 1.2.0? https://github.com/apache/incubator-gluten/releases/tag/v1.2.0
> 
> I am still unable to reproduce this issue.

Yes, the 1.2.0 version does not reproduce this issue. Thanks
