### ISSUE TITLE
[VL] IfThen sub-expressions are not all validated

### ISSUE THREAD

**Issue by wForget** [apache/incubator-gluten#7661]
### Backend

VL (Velox)

### Bug description

 Invalid regular expression, invalid escape sequence: \u

### Spark version

None

### Relevant logs

```bash
Exception: VeloxUserError
Error Source: USER
Error Code: INVALID_ARGUMENT
Reason: invalid regular expression:invalid escape sequence: \u
Retriable: False
Context: regexp_replace(n0_0, [\ud800\udc00-\udbff\udfff\ud800-\udfff]:VARCHAR, :VARCHAR, 1:INTEGER)
Additional Context: Top-level Expression: switch(or(isnull(n0_0), greaterthan(length(n0_0), 100:INTEGER)), :VARCHAR, regexp_replace(n0_0, [\ud800\udc00-\udbff\udfff\ud800-\udfff]:VARCHAR, :VARCHAR, 1:INTEGER))
Function: checkForBadPattern
File: /data/workspace/gluten-deploy-dist/ep/build-velox/build/velox_ep/velox/functions/sparksql/RegexFunctions.cpp
Line: 32
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_14VeloxUserErrorERKSsEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  _ZN8facebook5velox9functions8sparksql12_GLOBAL__N_121RegexpReplaceFunctionINS0_4exec10VectorExecEE14performReplaceERNS5_12StringWriterILb0EEERKNS0_10StringViewESD_SD_RKl
# 4  _ZN8facebook5velox9functions8sparksql12_GLOBAL__N_121RegexpReplaceFunctionINS0_4exec10VectorExecEE9callAsciiERNS5_12StringWriterILb0EEERKNS0_10StringViewESD_SD_RKl
# 5  _ZNK8facebook5velox4exec21SimpleFunctionAdapterINS0_4core9UDFHolderINS0_9functions8sparksql12_GLOBAL__N_121RegexpReplaceFunctionINS1_10VectorExecEEES9_NS0_7VarcharENS0_15ConstantCheckerIJSB_SB_SB_iEEEJSB_SB_SB_iEEEE5applyERKNS0_17SelectivityVectorERSt6vectorISt10shared_ptrINS0_10BaseVectorEESaISM_EERKSK_IKNS0_4TypeEERNS1_7EvalCtxERSM_
# 6  _ZN8facebook5velox4exec4Expr13applyFunctionERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt10shared_ptrINS0_10BaseVectorEE
# 7  _ZN8facebook5velox4exec4Expr11evalAllImplERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt10shared_ptrINS0_10BaseVectorEE
# 8  _ZN8facebook5velox4exec4Expr7evalAllERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt10shared_ptrINS0_10BaseVectorEE
# 9  _ZN8facebook5velox4exec4Expr13evalWithNullsERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt10shared_ptrINS0_10BaseVectorEE
# 10 _ZN8facebook5velox4exec4Expr13evalEncodingsERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt10shared_ptrINS0_10BaseVectorEE
# 11 _ZN8facebook5velox4exec4Expr4evalERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt10shared_ptrINS0_10BaseVectorEEPKNS1_7ExprSetE
# 12 _ZN8facebook5velox4exec10SwitchExpr15evalSpecialFormERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt10shared_ptrINS0_10BaseVectorEE
# 13 _ZN8facebook5velox4exec4Expr24evalSpecialFormWithStatsERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt10shared_ptrINS0_10BaseVectorEE
# 14 _ZN8facebook5velox4exec4Expr11evalAllImplERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt10shared_ptrINS0_10BaseVectorEE
# 15 _ZN8facebook5velox4exec4Expr7evalAllERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt10shared_ptrINS0_10BaseVectorEE
# 16 _ZN8facebook5velox4exec4Expr13evalWithNullsERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt10shared_ptrINS0_10BaseVectorEE
# 17 _ZN8facebook5velox4exec4Expr12evalWithMemoERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt10shared_ptrINS0_10BaseVectorEE
# 18 _ZN8facebook5velox4exec4Expr13evalEncodingsERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt10shared_ptrINS0_10BaseVectorEE
# 19 _ZN8facebook5velox4exec4Expr4evalERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt10shared_ptrINS0_10BaseVectorEEPKNS1_7ExprSetE
# 20 _ZN8facebook5velox4exec7ExprSet4evalEiibRKNS0_17SelectivityVectorERNS1_7EvalCtxERSt6vectorISt10shared_ptrINS0_10BaseVectorEESaISB_EE
# 21 _ZN8facebook5velox4exec13FilterProject7projectERKNS0_17SelectivityVectorERNS1_7EvalCtxE
# 22 _ZN8facebook5velox4exec13FilterProject9getOutputEv
# 23 _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE
# 24 _ZN8facebook5velox4exec6Driver4nextERSt10shared_ptrINS1_13BlockingStateEE
# 25 _ZN8facebook5velox4exec4Task4nextEPN5folly10SemiFutureINS3_4UnitEEE
# 26 _ZN6gluten24WholeStageResultIterator4nextEv
# 27 Java_org_apache_gluten_vectorized_ColumnarBatchOutIterator_nativeHasNext
# 28 0x00007fe91a8a46c7

	at org.apache.gluten.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
	at org.apache.gluten.vectorized.ColumnarBatchOutIterator.hasNextInternal(ColumnarBatchOutIterator.java:61)
	at org.apache.gluten.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:37)
	... 34 more

	at org.apache.gluten.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
	at org.apache.gluten.vectorized.ColumnarBatchOutIterator.hasNextInternal(ColumnarBatchOutIterator.java:61)
	at org.apache.gluten.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:37)
	... 21 more
```

**Comment by wForget** [comment]
Reproduce:

```
create table t1 (a string) stored as parquet;
insert into t1 values ('test');
select if(`a` IS NULL OR length(`a`) > 100, '', regexp_replace(`a`, '[\\u0000]', '')) AS `a` from t1;
```
