### ISSUE TITLE
Cannot support to generate Native FileScanRDD

### ISSUE THREAD

**Issue by Gustfh** [apache/incubator-gluten#785]
spark-sql select parquet table, got this issue.

java.lang.UnsupportedOperationException: Cannot support to generate Native FileScanRDD.
        at io.glutenproject.backendsapi.glutendata.GlutenIteratorApi.genNativeFileScanRDD(GlutenIteratorApi.scala:363)
        at io.glutenproject.execution.BasicScanExecTransformer.doExecuteColumnarInternal(BasicScanExecTransformer.scala:73)
        at io.glutenproject.execution.BasicScanExecTransformer.doExecuteColumnarInternal$(BasicScanExecTransformer.scala:49)
        at io.glutenproject.execution.FileSourceScanExecTransformer.doExecuteColumnarInternal(FileSourceScanExecTransformer.scala:37)
        at io.glutenproject.execution.FileSourceScanExecTransformer.doExecuteColumnar(FileSourceScanExecTransformer.scala:156)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:221)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229)
        at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:217)
        at org.apache.spark.sql.execution.GlutenColumnarToRowExec.doExecuteInternal(GlutenColumnarToRowExec.scala:76)
        at io.glutenproject.execution.GlutenColumnarToRowExecBase.doExecute(GlutenColumnarToRowExecBase.scala:50)

**Comment by gaoyangxiaozhu** [comment]
does this issue still exists or we can close this issue since it didn't share a detail context or reproduce steps ? @weiting-chen
