### ISSUE TITLE
[VL] write to ORC failed

### ISSUE THREAD

**Issue by FelixYBW** [apache/incubator-gluten#8068]
### Backend

VL (Velox)

### Bug description

write to ORC file get this error:

```
java.lang.UnsupportedOperationException
	at org.apache.spark.sql.execution.datasources.FakeRow.get(FakeRow.scala:71)
	at org.apache.spark.sql.hive.orc.OrcSerializer.wrapOrcStruct(OrcFileFormat.scala:268)
	at org.apache.spark.sql.hive.orc.OrcSerializer.serialize(OrcFileFormat.scala:228)
	at org.apache.spark.sql.hive.orc.OrcOutputWriter.write(OrcFileFormat.scala:298)
	at org.apache.spark.sql.execution.datasources.DynamicPartitionDataSingleWriter.writeStripe(FileFormatDataWriter.scala:443)
	at org.apache.spark.sql.execution.datasources.DynamicPartitionDataSingleWriter.write(FileFormatDataWriter.scala:431)
	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.writeWithMetrics(FileFormatDataWriter.scala:97)
	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.writeWithIterator(FileFormatDataWriter.scala:104)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeTask$1(FileFormatWriter.scala:409)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1505)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:418)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$write$17(FileFormatWriter.scala:326)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1471)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```
The SQL: `INSERT OVERWRITE TABLE xx`

@JkSelf do we support ORC write? Not sure why it doesn't fallback.

### Spark version

Spark-3.2.x

**Comment by JkSelf** [comment]
@FelixYBW It seems https://github.com/apache/incubator-gluten/pull/7996 has fixed this issue.

**Comment by FelixYBW** [comment]
Thank you, let me rebase and try
