### ISSUE TITLE
[CH]  `Cannot open file `: when try to open a tmp file for spilling aggregated data into disk

### ISSUE THREAD

**Issue by lgbo-ustc** [apache/incubator-gluten#8097]
### Backend

CH (ClickHouse)

### Bug description

[Expected behavior] and [actual behavior].

```
org.apache.gluten.exception.GlutenException: Cannot open file /tmp/libch/tmpa2e392b6-ff8b-4c77-ab45-fd3247739898: , errno: 2, strerror: No such file or directory: While executing GraceAggregatingTransform
0. ../contrib/llvm-project/libcxx/include/exception:141: Poco::Exception::Exception(String const&, int) @ 0x00000000150a54d9
1. ./build/../src/Common/Exception.cpp:109: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000006ad961c
2. ../src/Common/Exception.h:111: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000069c56ac
3. ../src/Common/Exception.h:222: DB::ErrnoException::ErrnoException(int, int, FormatStringHelperImpl::type>, String const&) @ 0x0000000006b1d775
4. ../src/Common/Exception.h:237: void DB::ErrnoException::throwFromPath(int, String const&, FormatStringHelperImpl::type>, String const&) @ 0x0000000006b1d4e8
5. ./build/../src/IO/OpenedFile.cpp:33: DB::OpenedFile::getFD() const @ 0x000000000eddecff
6. ../src/IO/ReadBufferFromFile.h:101: DB::ReadBufferFromFilePReadWithDescriptorsCache::ReadBufferFromFilePReadWithDescriptorsCache(String const&, unsigned long, int, char*, unsigned long, std::optional, std::shared_ptr) @ 0x000000000edd99d0
7. ../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:714: DB::createReadBufferFromFileBase(String const&, DB::ReadSettings const&, std::optional, std::optional, int, char*, unsigned long)::$_0::operator()(unsigned long, unsigned long, int) const @ 0x000000000edd94db
8. ./build/../src/Disks/IO/createReadBufferFromFileBase.cpp:213: DB::createReadBufferFromFileBase(String const&, DB::ReadSettings const&, std::optional, std::optional, int, char*, unsigned long) @ 0x000000000edd93ee
9. ./build/../src/Disks/DiskLocal.cpp:331: DB::DiskLocal::readFile(String const&, DB::ReadSettings const&, std::optional, std::optional) const @ 0x000000000f54a998
10. ./build/../src/Interpreters/TemporaryDataOnDisk.cpp:142: DB::TemporaryFileOnLocalDisk::read(unsigned long) const @ 0x00000000103b254d
11. ./build/../src/Interpreters/TemporaryDataOnDisk.cpp:297: DB::TemporaryDataBuffer::read() @ 0x00000000103b07f7
12. ./build/../src/Interpreters/TemporaryDataOnDisk.cpp:360: DB::TemporaryBlockStreamHolder::getReadStream() const @ 0x00000000103b0c77
13. ./build/../utils/extern-local-engine/Operator/GraceAggregatingTransform.cpp:401: local_engine::GraceAggregatingTransform::prepareBucketOutputBlocks(unsigned long) @ 0x00000000070a2f5d
14. ./build/../utils/extern-local-engine/Operator/GraceAggregatingTransform.cpp:158: local_engine::GraceAggregatingTransform::work() @ 0x00000000070a1168
15. ./build/../src/Processors/Executors/ExecutionThreadContext.cpp:47: DB::ExecutionThreadContext::executeTask() @ 0x00000000119d46e2
16. ./build/../src/Processors/Executors/PipelineExecutor.cpp:289: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic*) @ 0x00000000119c99df
17. ./build/../src/Processors/Executors/PipelineExecutor.cpp:255: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x00000000119c919d
18. ./build/../src/Processors/Executors/PipelineExecutor.cpp:126: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x00000000119c8f8b
19. ./build/../utils/extern-local-engine/Parser/LocalExecutor.cpp:130: local_engine::LocalExecutor::execute() @ 0x0000000006eb7402
20. ./build/../utils/extern-local-engine/local_engine_jni.cpp:606: buildAndExecuteShuffle @ 0x00000000069b1884
21. ./build/../utils/extern-local-engine/local_engine_jni.cpp:726: Java_org_apache_gluten_vectorized_CHShuffleSplitterJniWrapper_nativeMakeForRSS @ 0x00000000069b353c

	at org.apache.gluten.vectorized.CHShuffleSplitterJniWrapper.nativeMakeForRSS(Native Method)
	at org.apache.gluten.vectorized.CHShuffleSplitterJniWrapper.makeForRSS(CHShuffleSplitterJniWrapper.java:73)
	at org.apache.spark.shuffle.CHCelebornColumnarShuffleWriter.internalWrite(CHCelebornColumnarShuffleWriter.scala:87)
	at org.apache.spark.shuffle.CelebornColumnarShuffleWriter.write(CelebornColumnarShuffleWriter.scala:119)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:60)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### Spark version

None

**Comment by lgbo-ustc** [comment]
May be caused by https://github.com/apache/incubator-gluten/pull/7968/files

**Comment by lgbo-ustc** [comment]
`spark.gluten.sql.columnar.backend.ch.runtime_config.use_current_directory_as_tmp` is fase at default
