### ISSUE TITLE
[VL] Publish Gluten modified Arrow jar

### ISSUE THREAD

**Issue by zhztheplayer** [apache/incubator-gluten#8228]
### Problem description

The Arrow jar Velox backend is using is not publicly accessible and is required to be build locally. We'd either push the modified code to upstream or publish the modified Jar to a public accessible Maven repo.

Doing this will perhaps:

1. Avoid compiling Arrow before building Velox backend (@PHILO-HE please confirm, thanks)
2. Make it easier to verify Velox backend's Maven build without building the Arrow code in advance. Say if one doesn't ever build the Arrow jar, they can still compile Velox backend's code without "dependency not found" error.

### System information

N/A

**Comment by FelixYBW** [comment]
What's the modified code? is it all here? https://github.com/apache/incubator-gluten/blob/main/ep/build-velox/src/modify_arrow.patch

**Comment by jinchengchenghh** [comment]
We modify the code for CSV reader, https://github.com/apache/incubator-gluten/blob/main/ep/build-velox/src/modify_arrow_dataset_scan_option.patch

The code has merged in Apache Arrow but in version 18, we could not upgrade to arrow version 18 because it drops JDK8 support.

We upload ourself Protobuf jar to io.glutenproject.protobuf nexus repo, we cannot upload arrow jar to org.apache.gluten.arrow artifact because we don't have the privilege.

We could drop csv options after we move to velox csv reader which is in progress https://github.com/facebookincubator/velox/discussions/11425

**Comment by zhztheplayer** [comment]
> We cannot upload arrow jar to org.apache.gluten.arrow artifact because we don't have the privilege.

Right, definitely. If no other ways, we can continue the use of `io.glutenproject` or something like that. Doing this would not violate the ASF's policy.

> We could drop csv options after we move to velox csv reader which is in progress https://github.com/facebookincubator/velox/discussions/11425

Yes, though we'd better to have a short-term solution either.

**Comment by jinchengchenghh** [comment]
Alternatively, we could drop the options since no one requests the option. I don't map the current Spark option with Arrow option. No one reports the issue, we now fallback if the option is different with default option.

**Comment by jinchengchenghh** [comment]
It will take many efforts to upload Arrow jar to io.glutenproject.

**Comment by PHILO-HE** [comment]
> Avoid compiling Arrow before building Velox backend (@PHILO-HE please confirm, thanks)

@zhztheplayer, maybe it's correct. For native arrow lib, one-time installation is enough. If it is not installed, bundled building may also work well for both velox and gluten cpp.

**Comment by FelixYBW** [comment]
> Alternatively, we could drop the options since no one requests the option. I don't map the current Spark option with Arrow option. No one reports the issue, we now fallback if the option is different with default option.

Let's drop the options then. As you said there is no customer use it so far.

**Comment by jinchengchenghh** [comment]
Yes, I will draft a PR to drop it.

**Comment by jinchengchenghh** [comment]
I find a problem, we don't need Spark option, but we really need to send the schema by Arrow option, if we don't send it, the data type is usually different with required type, because arrow infers the data type in that case, so we cannot drop csv option support.

Arrow JNI also needs to build the arrow java code in case of a core dump problem, so do we need to publish it? I don't know if our version can solve this issue.

CC @PHILO-HE @zhouyuan

**Comment by FelixYBW** [comment]
If so, let's keep the patches

**Comment by jinchengchenghh** [comment]
I also find a problem, our protobuf version is 3.23.4, but arrow 15 protobuf version is 2.5.0,
I update the version in the patch
https://github.com/apache/incubator-gluten/blob/main/ep/build-velox/src/modify_arrow_dataset_scan_option.patch#L158
So it has conflicts, dataset.jni.NativeMemoryPool will throw exception when switch to apache arrow 15.0.0:
```
24/12/20 10:38:53 ERROR TaskResources: Task 1 failed by error:
java.lang.UnsatisfiedLinkError: /tmp/jnilib-2731956626225475599.tmp: /tmp/jnilib-2731956626225475599.tmp: undefined symbol: _ZTIN6google8protobuf7MessageE
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
        at java.lang.Runtime.load0(Runtime.java:782)
        at java.lang.System.load(System.java:1100)
        at org.apache.arrow.dataset.jni.JniLoader.load(JniLoader.java:92)
        at org.apache.arrow.dataset.jni.JniLoader.loadRemaining(JniLoader.java:75)
        at org.apache.arrow.dataset.jni.JniLoader.ensureLoaded(JniLoader.java:61)
        at org.apache.arrow.dataset.jni.NativeMemoryPool.createListenable(NativeMemoryPool.java:44)
        at org.apache.gluten.memory.arrow.pool.ArrowNativeMemoryPool.<init>(ArrowNativeMemoryPool.java:34)
        at org.apache.gluten.memory.arrow.pool.ArrowNativeMemoryPool.createArrowNativeMemoryPool(ArrowNativeMemoryPool.java:47)
        at org.apache.gluten.memory.arrow.pool.ArrowNativeMemoryPool.lambda$arrowPool$0(ArrowNativeMemoryPool.java:42)
        at org.apache.spark.task.TaskResourceRegistry.$anonfun$addResourceIfNotRegistered$1(TaskResources.scala:344)
        at org.apache.spark.task.TaskResourceRegistry.lock(TaskResources.scala:264)
        at org.apache.spark.task.TaskResourceRegistry.addResourceIfNotRegistered(TaskResources.scala:340)
        at org.apache.spark.task.TaskResources$.addResourceIfNotRegistered(TaskResources.scala:176)
        at org.apache.spark.task.TaskResources.addResourceIfNotRegistered(TaskResources.scala)
        at org.apache.gluten.memory.arrow.pool.ArrowNativeMemoryPool.arrowPool(ArrowNativeMemoryPool.java:42)
        at org.apache.gluten.datasource.ArrowCSVFileFormat.pool$lzycompute(ArrowCSVFileFormat.scala:64)
```
